# docker-compose.yml

version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  vector-api:
    build: .
    container_name: vector-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - HOST=qdrant
      - PORT=6333
      - COLLECTION_NAME=products_fast
      - VECTOR_SIZE=384
      - MODEL_NAME=BAAI/bge-small-en-v1.5
      - CROSS_ENCODER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
      - SEARCH_LIMIT=100
      - SCORE_THRESHOLD=0.7
      - LOG_LEVEL=INFO
      - LOG_PATH=logs/service.log
      - MAX_SEARCH_THREADS=4
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - TOKENIZERS_PARALLELISM=true
      - SPELLCHECK=true
      - DEBUG_UI=false
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  vector-ui:
    build: .
    container_name: vector-ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - SEARCH_API_HOST=vector-api
      - SEARCH_API_PORT=8000
      - SEARCH_ENDPOINT_TYPE=fusion
      - SHOW_SEARCH_TYPE_SELECTOR=true
      - SHOW_PERFORMANCE_STATS=true
      - DEBUG_UI=false
    depends_on:
      vector-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: ["streamlit", "run", "search_ui/search.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

volumes:
  qdrant_data:
